### ISSUE TITLE
Request for enhancement to the implementation

### ISSUE THREAD

**Issue by amirsoroush** [amirrezaes/Simple-Hash-Table#1]
Hi,

Do you have any plans to further improve the implementation of your hash table? like adding an optional threshold value before extending, or supporting for other strategies to resolve the collisions? perhaps accepting other types of hashable objects?

**Comment by amirrezaes** [comment]
Hello
I wrote this two years ago, and since then I have gotten more efficient both with python and algorithms. I can see some pitfalls and inefficiencies in the code; perhaps I need to solve them before going any further.
